# XRF Active Learning

A very basic example of actively learning the composition map of a combintorial wafer from X-ray Fluorescence Spectroscopy data. 

# Set up the Python Environment

In [54]:
import numpy as np
import pandas as pd

In [55]:
import sys, os 

In [56]:
sys.path

['C:\\Users\\asm6\\hermes\\hermes\\hermes\\XRF_wafer_example',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\python39.zip',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\DLLs',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes',
 '',
 'C:\\Users\\asm6\\AppData\\Roaming\\Python\\Python39\\site-packages',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib\\site-packages',
 'c:\\users\\asm6\\tools-cp-porousmat\\src',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib\\site-packages\\win32',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\asm6\\Anaconda3\\envs\\hermes\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\asm6\\.ipython']

# Reading some pre-collected data 

In [57]:
data = pd.read_csv("CoCrAl_Wafer_XRF_Summary_for_SLAC.csv")

In [58]:
data

Spot x  Spot y  Spot #  Lyr #1(um)  Si-At.%  Al-At.%  Cr-At.%  Co-At.%  \
0     -9.04  -31.64       1       0.089      100   22.357   38.642   39.001   
1     -4.52  -31.64       2       0.092      100   20.383   38.752   40.865   
2      0.00  -31.64       3       0.093      100   18.784   38.381   42.835   
3      4.52  -31.64       4       0.094      100   17.528   37.847   44.625   
4      9.04  -31.64       5       0.093      100   16.068   37.085   46.847   
..      ...     ...     ...         ...      ...      ...      ...      ...   
172   -9.04   31.64     173       0.118      100   33.586   12.716   53.698   
173   -4.52   31.64     174       0.122      100   30.601   12.442   56.957   
174    0.00   31.64     175       0.124      100   27.627   12.238   60.135   
175    4.52   31.64     176       0.123      100   23.418   12.111   64.471   
176    9.04   31.64     177       0.123      100   21.071   11.663   67.266   

     Al-Int(c/s)  Err(c/s)  ...  Si-Int(c/s)  Err(c/s).2  Err(c/s).3  \
0         50.070     3.298  ...     3272.563      25.449           0   
1         47.187     3.203  ...     3198.343      25.157           0   
2         44.283     3.111  ...     3123.742      24.865           0   
3         41.793     3.030  ...     3098.830      24.764           0   
4         38.071     2.901  ...     3080.151      24.686           0   
..           ...       ...  ...          ...         ...         ...   
172       94.021     4.417  ...     2766.827      23.398           0   
173       88.542     4.291  ...     2672.276      22.991           0   
174       80.925     4.103  ...     2586.545      22.622           0   
175       68.202     3.783  ...     2515.512      22.307           0   
176       61.187     3.591  ...     2477.260      22.144           0   

     Cr-Int(c/s)  Err(c/s).4  Err(c/s).5  Co-Int(c/s)  Err(c/s).6  Err(c/s).7  \
0       1121.635      13.194       0.455     1332.952      14.433       0.422   
1       1175.860      13.505       0.445     1457.241      15.080       0.423   
2       1197.316      13.626       0.437     1566.973      15.638       0.427   
3       1203.193      13.664       0.430     1660.246      16.085       0.432   
4       1178.450      13.521       0.425     1737.917      16.454       0.444   
..           ...         ...         ...          ...         ...         ...   
172      526.230       9.063       0.219     2380.162      19.227       0.434   
173      545.399       9.227       0.210     2652.644      20.288       0.436   
174      553.844       9.300       0.205     2870.762      21.103       0.442   
175      556.511       9.322       0.203     3098.652      21.915       0.456   
176      543.548       9.217       0.198     3254.520      22.464       0.464   

     LT(secs)  
0      60.028  
1      60.031  
2      60.022  
3      60.031  
4      60.039  
..        ...  
172    60.045  
173    60.058  
174    60.047  
175    60.051  
176    60.026  

[177 rows x 21 columns]

In [59]:
def simulated_measurement(locations):
    
    measurements = np.array([]).reshape(-1,3)
    
    for location in locations:
        
        mask_x = data["Spot x"] == location[0]    
        mask_y = data["Spot y"] == location[1]

        mask = mask_x * mask_y
    
        Al = data[mask]["Al-At.%"].to_numpy()[0]
        Cr = data[mask]["Cr-At.%"].to_numpy()[0]
        Co = data[mask]["Co-At.%"].to_numpy()[0]
        
        meas = np.array([Al, Cr, Co]).reshape(-1,3)
        
        measurements = np.concatenate((measurements, meas), axis=0)
    
    return measurements

# Build Data Pipeline

In [67]:
%pip install /Users/asm6/hermes/hermes

Processing c:\users\asm6\hermes\hermes
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Created wheel for hermes: filename=hermes-0.1.0-py3-none-any.whl size=55822 sha256=37c8905e762f26edd7e7e425cf4a2f8385a11ebb0af49af0b7b6c6a5f1b046aa
  Stored in directory: C:\Users\asm6\AppData\Local\Temp\1\pip-ephem-wheel-cache-s7_b8i89\wheels\2e\10\ce\a2f6e25d7ef678e552faae26ffff95f978780433cb0c0165ab
Successfully built hermes
Note: you may need to restart the kernel to use updated packages.


  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.


In [72]:
from hermes.distance import *

#Distance Metric in Location-Space:
#Euclidean (distance between points on the wafer)
location_distance = EuclidianDistance

#Distance Metric in Measurement-Space:
#Euclidean (distance between points on the simplex of compositions)
measurement_distance = EuclidianDistance


In [71]:
EuclidianDistance

hermes.distance.distance.EuclidianDistance

# Set up AL

In [39]:
#Set up the domain
x = data["Spot x"].to_numpy()
y = data["Spot y"].to_numpy()

locations = np.concatenate((x.reshape(-1,1), y.reshape(-1,1)), axis = 1)
locations

array([[ -9.04, -31.64],
       [ -4.52, -31.64],
       [  0.  , -31.64],
       [  4.52, -31.64],
       [  9.04, -31.64],
       [-18.08, -27.12],
       [-13.56, -27.12],
       [ -9.04, -27.12],
       [ -4.52, -27.12],
       [  0.  , -27.12],
       [  4.52, -27.12],
       [  9.04, -27.12],
       [ 13.56, -27.12],
       [ 18.08, -27.12],
       [-22.6 , -22.6 ],
       [-18.08, -22.6 ],
       [-13.56, -22.6 ],
       [ -9.04, -22.6 ],
       [ -4.52, -22.6 ],
       [  0.  , -22.6 ],
       [  4.52, -22.6 ],
       [  9.04, -22.6 ],
       [ 13.56, -22.6 ],
       [ 18.08, -22.6 ],
       [ 22.6 , -22.6 ],
       [-27.12, -18.08],
       [-22.6 , -18.08],
       [-18.08, -18.08],
       [-13.56, -18.08],
       [ -9.04, -18.08],
       [ -4.52, -18.08],
       [  0.  , -18.08],
       [  4.52, -18.08],
       [  9.04, -18.08],
       [ 13.56, -18.08],
       [ 18.08, -18.08],
       [ 22.6 , -18.08],
       [ 27.12, -18.08],
       [-27.12, -13.56],
       [-22.6 , -13.56],


## Low level specifcation

In [46]:
#Containers for results
measured_locations = np.array([]).reshape(-1,2)
measurements = np.array([]).reshape(-1,3)

#AL loop properties
loops = 10
start_measurements = 5


In [47]:
#Initialize:
random_number_generator = np.random.default_rng()
next_locations = random_number_generator.choice(locations, start_measurements)

measured_locations = np.concatenate((measured_locations, next_locations), axis = 0)

for loop in range(loops):
    #Measure
    #Measured at the new locations:
    new_measurements = simulated_measurement(next_locations)
    #Append those measurments to the list of total measurements
    measurements = np.concatenate((measurements, new_measurements), axis = 0)
    
    #Regression
    
    
    #Acquire
    
    #Archive
    

# Scratch

In [73]:
new_measurements

array([[15.276, 18.66 , 66.063],
       [13.515, 18.011, 68.474],
       [37.547, 21.598, 40.854],
       [29.598, 27.701, 42.7  ],
       [39.625, 19.583, 40.791]])

In [74]:
measured_locations

array([[ 18.08,   4.52],
       [ 22.6 ,   4.52],
       [-22.6 ,   4.52],
       [-13.56,  -9.04],
       [-22.6 ,   9.04]])

In [80]:
location_distance_table = location_distance.calculate(measured_locations)
location_distance_table

array([[ 0.        ,  4.52      , 40.68      , 34.42329444, 40.93034082],
       [ 4.52      ,  0.        , 45.2       , 38.61889693, 45.42543781],
       [40.68      , 45.2       ,  0.        , 16.29709177,  4.52      ],
       [34.42329444, 38.61889693, 16.29709177,  0.        , 20.21405452],
       [40.93034082, 45.42543781,  4.52      , 20.21405452,  0.        ]])

In [82]:
measurement_distance_table = measurement_distance.calculate(new_measurements)
measurement_distance_table

array([[ 0.        ,  3.05536299, 33.76570695, 28.85635344, 35.10555104],
       [ 3.05536299,  0.        , 36.78679101, 31.88821201, 38.08610997],
       [33.76570695, 36.78679101,  0.        , 10.1902368 ,  2.8952164 ],
       [28.85635344, 31.88821201, 10.1902368 ,  0.        , 13.04173815],
       [35.10555104, 38.08610997,  2.8952164 , 13.04173815,  0.        ]])